<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2015-05-04T10:05:26+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 10;
	$section_id = 11;
	$post_id    = 1;
	$post_section = 11;
	require('../../index.php');
// *************************************************
