<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2015-05-04T09:39:26+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 12;
	require('../index.php');
// *************************************************
